//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("CAModel1", "FK_JY_CASEP_REFERENCE_JY_CASE", "JY_Case", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Web.Areas.JobArrangements.Models.JY_Case), "JY_CasePersonal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Web.Areas.JobArrangements.Models.JY_CasePersonal), true)]

#endregion

namespace Web.Areas.JobArrangements.Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class CAEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“CAEntities”部分中的连接字符串初始化新 CAEntities 对象。
        /// </summary>
        public CAEntities() : base("name=CAEntities", "CAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 CAEntities 对象。
        /// </summary>
        public CAEntities(string connectionString) : base(connectionString, "CAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 CAEntities 对象。
        /// </summary>
        public CAEntities(EntityConnection connection) : base(connection, "CAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<JY_Case> JY_Case
        {
            get
            {
                if ((_JY_Case == null))
                {
                    _JY_Case = base.CreateObjectSet<JY_Case>("JY_Case");
                }
                return _JY_Case;
            }
        }
        private ObjectSet<JY_Case> _JY_Case;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<JY_CasePersonal> JY_CasePersonal
        {
            get
            {
                if ((_JY_CasePersonal == null))
                {
                    _JY_CasePersonal = base.CreateObjectSet<JY_CasePersonal>("JY_CasePersonal");
                }
                return _JY_CasePersonal;
            }
        }
        private ObjectSet<JY_CasePersonal> _JY_CasePersonal;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 JY_Case EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToJY_Case(JY_Case jY_Case)
        {
            base.AddObject("JY_Case", jY_Case);
        }
    
        /// <summary>
        /// 用于向 JY_CasePersonal EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToJY_CasePersonal(JY_CasePersonal jY_CasePersonal)
        {
            base.AddObject("JY_CasePersonal", jY_CasePersonal);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CAModel1", Name="JY_Case")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class JY_Case : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 JY_Case 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static JY_Case CreateJY_Case(global::System.Int32 id)
        {
            JY_Case jY_Case = new JY_Case();
            jY_Case.ID = id;
            return jY_Case;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CName
        {
            get
            {
                return _CName;
            }
            set
            {
                OnCNameChanging(value);
                ReportPropertyChanging("CName");
                _CName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CName");
                OnCNameChanged();
            }
        }
        private global::System.String _CName;
        partial void OnCNameChanging(global::System.String value);
        partial void OnCNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CDate
        {
            get
            {
                return _CDate;
            }
            set
            {
                OnCDateChanging(value);
                ReportPropertyChanging("CDate");
                _CDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CDate");
                OnCDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CDate;
        partial void OnCDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CSummary
        {
            get
            {
                return _CSummary;
            }
            set
            {
                OnCSummaryChanging(value);
                ReportPropertyChanging("CSummary");
                _CSummary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CSummary");
                OnCSummaryChanged();
            }
        }
        private global::System.String _CSummary;
        partial void OnCSummaryChanging(global::System.String value);
        partial void OnCSummaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CDate_S
        {
            get
            {
                return _CDate_S;
            }
            set
            {
                OnCDate_SChanging(value);
                ReportPropertyChanging("CDate_S");
                _CDate_S = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CDate_S");
                OnCDate_SChanged();
            }
        }
        private Nullable<global::System.DateTime> _CDate_S;
        partial void OnCDate_SChanging(Nullable<global::System.DateTime> value);
        partial void OnCDate_SChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CDate_E
        {
            get
            {
                return _CDate_E;
            }
            set
            {
                OnCDate_EChanging(value);
                ReportPropertyChanging("CDate_E");
                _CDate_E = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CDate_E");
                OnCDate_EChanged();
            }
        }
        private Nullable<global::System.DateTime> _CDate_E;
        partial void OnCDate_EChanging(Nullable<global::System.DateTime> value);
        partial void OnCDate_EChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AttachmentID
        {
            get
            {
                return _AttachmentID;
            }
            set
            {
                OnAttachmentIDChanging(value);
                ReportPropertyChanging("AttachmentID");
                _AttachmentID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AttachmentID");
                OnAttachmentIDChanged();
            }
        }
        private global::System.String _AttachmentID;
        partial void OnAttachmentIDChanging(global::System.String value);
        partial void OnAttachmentIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Years
        {
            get
            {
                return _Years;
            }
            set
            {
                OnYearsChanging(value);
                ReportPropertyChanging("Years");
                _Years = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Years");
                OnYearsChanged();
            }
        }
        private Nullable<global::System.Int32> _Years;
        partial void OnYearsChanging(Nullable<global::System.Int32> value);
        partial void OnYearsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CStatus
        {
            get
            {
                return _CStatus;
            }
            set
            {
                OnCStatusChanging(value);
                ReportPropertyChanging("CStatus");
                _CStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CStatus");
                OnCStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _CStatus;
        partial void OnCStatusChanging(Nullable<global::System.Int32> value);
        partial void OnCStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CResult
        {
            get
            {
                return _CResult;
            }
            set
            {
                OnCResultChanging(value);
                ReportPropertyChanging("CResult");
                _CResult = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CResult");
                OnCResultChanged();
            }
        }
        private global::System.String _CResult;
        partial void OnCResultChanging(global::System.String value);
        partial void OnCResultChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatorId
        {
            get
            {
                return _CreatorId;
            }
            set
            {
                OnCreatorIdChanging(value);
                ReportPropertyChanging("CreatorId");
                _CreatorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatorId");
                OnCreatorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatorId;
        partial void OnCreatorIdChanging(Nullable<global::System.Int32> value);
        partial void OnCreatorIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateOn
        {
            get
            {
                return _CreateOn;
            }
            set
            {
                OnCreateOnChanging(value);
                ReportPropertyChanging("CreateOn");
                _CreateOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateOn");
                OnCreateOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateOn;
        partial void OnCreateOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateOnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdaterId
        {
            get
            {
                return _UpdaterId;
            }
            set
            {
                OnUpdaterIdChanging(value);
                ReportPropertyChanging("UpdaterId");
                _UpdaterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdaterId");
                OnUpdaterIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdaterId;
        partial void OnUpdaterIdChanging(Nullable<global::System.Int32> value);
        partial void OnUpdaterIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateOn
        {
            get
            {
                return _LastUpdateOn;
            }
            set
            {
                OnLastUpdateOnChanging(value);
                ReportPropertyChanging("LastUpdateOn");
                _LastUpdateOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateOn");
                OnLastUpdateOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateOn;
        partial void OnLastUpdateOnChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateOnChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CAModel1", "FK_JY_CASEP_REFERENCE_JY_CASE", "JY_CasePersonal")]
        public EntityCollection<JY_CasePersonal> JY_CasePersonal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<JY_CasePersonal>("CAModel1.FK_JY_CASEP_REFERENCE_JY_CASE", "JY_CasePersonal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<JY_CasePersonal>("CAModel1.FK_JY_CASEP_REFERENCE_JY_CASE", "JY_CasePersonal", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CAModel1", Name="JY_CasePersonal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class JY_CasePersonal : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 JY_CasePersonal 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static JY_CasePersonal CreateJY_CasePersonal(global::System.Int32 id)
        {
            JY_CasePersonal jY_CasePersonal = new JY_CasePersonal();
            jY_CasePersonal.ID = id;
            return jY_CasePersonal;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JY_Case_ID
        {
            get
            {
                return _JY_Case_ID;
            }
            set
            {
                OnJY_Case_IDChanging(value);
                ReportPropertyChanging("JY_Case_ID");
                _JY_Case_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JY_Case_ID");
                OnJY_Case_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _JY_Case_ID;
        partial void OnJY_Case_IDChanging(Nullable<global::System.Int32> value);
        partial void OnJY_Case_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JY_Personnel_ID
        {
            get
            {
                return _JY_Personnel_ID;
            }
            set
            {
                OnJY_Personnel_IDChanging(value);
                ReportPropertyChanging("JY_Personnel_ID");
                _JY_Personnel_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JY_Personnel_ID");
                OnJY_Personnel_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _JY_Personnel_ID;
        partial void OnJY_Personnel_IDChanging(Nullable<global::System.Int32> value);
        partial void OnJY_Personnel_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JY_Examine_ID
        {
            get
            {
                return _JY_Examine_ID;
            }
            set
            {
                OnJY_Examine_IDChanging(value);
                ReportPropertyChanging("JY_Examine_ID");
                _JY_Examine_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JY_Examine_ID");
                OnJY_Examine_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _JY_Examine_ID;
        partial void OnJY_Examine_IDChanging(Nullable<global::System.Int32> value);
        partial void OnJY_Examine_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JY_Record_ID
        {
            get
            {
                return _JY_Record_ID;
            }
            set
            {
                OnJY_Record_IDChanging(value);
                ReportPropertyChanging("JY_Record_ID");
                _JY_Record_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JY_Record_ID");
                OnJY_Record_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _JY_Record_ID;
        partial void OnJY_Record_IDChanging(Nullable<global::System.Int32> value);
        partial void OnJY_Record_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatorId
        {
            get
            {
                return _CreatorId;
            }
            set
            {
                OnCreatorIdChanging(value);
                ReportPropertyChanging("CreatorId");
                _CreatorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatorId");
                OnCreatorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatorId;
        partial void OnCreatorIdChanging(Nullable<global::System.Int32> value);
        partial void OnCreatorIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateOn
        {
            get
            {
                return _CreateOn;
            }
            set
            {
                OnCreateOnChanging(value);
                ReportPropertyChanging("CreateOn");
                _CreateOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateOn");
                OnCreateOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateOn;
        partial void OnCreateOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateOnChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdaterId
        {
            get
            {
                return _UpdaterId;
            }
            set
            {
                OnUpdaterIdChanging(value);
                ReportPropertyChanging("UpdaterId");
                _UpdaterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdaterId");
                OnUpdaterIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdaterId;
        partial void OnUpdaterIdChanging(Nullable<global::System.Int32> value);
        partial void OnUpdaterIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateOn
        {
            get
            {
                return _LastUpdateOn;
            }
            set
            {
                OnLastUpdateOnChanging(value);
                ReportPropertyChanging("LastUpdateOn");
                _LastUpdateOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateOn");
                OnLastUpdateOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateOn;
        partial void OnLastUpdateOnChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateOnChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CAModel1", "FK_JY_CASEP_REFERENCE_JY_CASE", "JY_Case")]
        public JY_Case JY_Case
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JY_Case>("CAModel1.FK_JY_CASEP_REFERENCE_JY_CASE", "JY_Case").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JY_Case>("CAModel1.FK_JY_CASEP_REFERENCE_JY_CASE", "JY_Case").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<JY_Case> JY_CaseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JY_Case>("CAModel1.FK_JY_CASEP_REFERENCE_JY_CASE", "JY_Case");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<JY_Case>("CAModel1.FK_JY_CASEP_REFERENCE_JY_CASE", "JY_Case", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
