//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.JobArrangements.Models
{
    using System;
    using System.Collections.Generic;
	using JiYun.Web.Models;
	using System.ComponentModel.DataAnnotations;
    
    public partial class JobArrangement:BaseModel
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Category { get; set; }
        public string Content { get; set; }
        public Nullable<int> CreatorNo { get; set; }
        public string DoerNoList { get; set; }
        public Nullable<int> SupervisorNo { get; set; }
        public Nullable<int> AppointStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Starttime { get; set; }
        public Nullable<System.DateTime> Endtime { get; set; }
        public string LoopCategory { get; set; }
    }
    
}
