//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.Mes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=JiYun")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
            //throw new UnintentionalCodeFirstException();
        //}
    
        public DbSet<X_Messages> X_Messages { get; set; }
        public DbSet<X_MsgAtts> X_MsgAtts { get; set; }
        public DbSet<X_Notice> X_Notice { get; set; }
        public DbSet<X_NoticeDetail> X_NoticeDetail { get; set; }
        public DbSet<X_ScheduleDetails> X_ScheduleDetails { get; set; }
        public DbSet<X_Schedules> X_Schedules { get; set; }
        public DbSet<X_SMS> X_SMS { get; set; }
        public DbSet<X_UserMesCounts> X_UserMesCounts { get; set; }
        public DbSet<X_UserMessages> X_UserMessages { get; set; }
    }
}
