//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.Mes.Models
{
    using System;
    using System.Collections.Generic;
	using JiYun.Web.Models;
	using System.ComponentModel.DataAnnotations;
    
    public partial class X_MsgAtts:BaseModel
    {
        public Nullable<int> X_Messages_ID { get; set; }
        public Nullable<int> AttID { get; set; }
    
    	[ForeignKey("X_Messages_ID")]
        public virtual X_Messages X_Messages { get; set; }
    }
    
}
