//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.Mes.Models
{
    using System;
    using System.Collections.Generic;
	using JiYun.Web.Models;
	using System.ComponentModel.DataAnnotations;
    
    public partial class X_NoticeDetail:BaseModel
    {
        public Nullable<int> DeptID { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> X_Notice_ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UName { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public string ReadRemark { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
    	[ForeignKey("X_Notice_ID")]
        public virtual X_Notice X_Notice { get; set; }
    }
    
}
