//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.Mes.Models
{
    using System;
    using System.Collections.Generic;
	using JiYun.Web.Models;
	using System.ComponentModel.DataAnnotations;
    
    public partial class X_ScheduleDetails:BaseModel
    {
        public Nullable<int> UserID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> X_Schedules_ID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<bool> IsExpired { get; set; }
    
    	[ForeignKey("X_Schedules_ID")]
        public virtual X_Schedules X_Schedules { get; set; }
    }
    
}
