//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.Mes.Models
{
    using System;
    using System.Collections.Generic;
	using JiYun.Web.Models;
	using System.ComponentModel.DataAnnotations;
    
    public partial class X_Schedules:BaseModel
    {
        public X_Schedules()
        {
            this.X_Messages = new HashSet<X_Messages>();
            this.X_ScheduleDetails = new HashSet<X_ScheduleDetails>();
            this.X_SMS = new HashSet<X_SMS>();
        }
    
        public Nullable<int> UserID { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Address { get; set; }
        public string Color { get; set; }
        public Nullable<int> IsRemind { get; set; }
        public Nullable<int> RemindDays { get; set; }
        public string RemindType { get; set; }
        public Nullable<int> RemindRecyle { get; set; }
        public Nullable<int> IsPublic { get; set; }
        public string NviteUsers { get; set; }
        public Nullable<int> ScType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string RemaindCode { get; set; }
        public Nullable<int> RemainBl { get; set; }
        public Nullable<System.DateTime> LastRemaindTime { get; set; }
    
        public virtual ICollection<X_Messages> X_Messages { get; set; }
        public virtual ICollection<X_ScheduleDetails> X_ScheduleDetails { get; set; }
        public virtual ICollection<X_SMS> X_SMS { get; set; }
    }
    
}
