//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBService.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations.Schema;
	using JiYun.Web.Models;
	using System.ComponentModel.DataAnnotations;
    
    public partial class AssetInfos:BaseModel
    {
        public AssetInfos()
        {
            this.AccidentalMaintenances = new HashSet<AccidentalMaintenances>();
            this.AssetOptionalProperties = new HashSet<AssetOptionalProperties>();
            this.MaintainRequests = new HashSet<MaintainRequests>();
        }
    
        public string AssetName { get; set; }
        public string AssetBrand { get; set; }
        public Nullable<int> AssetCategoryNo { get; set; }
        public string ImagePath { get; set; }
        public string AllocatedIp { get; set; }
        public string LoginName { get; set; }
        public string LoginPassword { get; set; }
        public Nullable<int> IsImportanAsset { get; set; }
        public Nullable<int> AssetTypeNo { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> MaxServiceYear { get; set; }
        public Nullable<System.DateTime> BoughtTime { get; set; }
        public Nullable<System.DateTime> MaintainStarttime { get; set; }
        public Nullable<System.DateTime> MaintainEndtime { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsSelfOwned { get; set; }
        public string OS { get; set; }
    
        public virtual ICollection<AccidentalMaintenances> AccidentalMaintenances { get; set; }
    	[ForeignKey("CabinetInfos_ID")]
        public virtual CabinetInfos CabinetInfos { get; set; }
    	[ForeignKey("MerchantInfos_ID")]
        public virtual MerchantInfos MerchantInfos { get; set; }
    	[ForeignKey("MotorRoomInfos_ID")]
        public virtual MotorRoomInfos MotorRoomInfos { get; set; }
    	[ForeignKey("UserCompanyInfos_ID")]
        public virtual UserCompanyInfos UserCompanyInfos { get; set; }
        public virtual ICollection<AssetOptionalProperties> AssetOptionalProperties { get; set; }
        public virtual ICollection<MaintainRequests> MaintainRequests { get; set; }
    }
    
}
