//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBService.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations.Schema;
	using JiYun.Web.Models;
	using System.ComponentModel.DataAnnotations;
    
    public partial class AssetOptionalProperties:BaseModel
    {
        public Nullable<int> DeviceCategoryNo { get; set; }
        public string Value { get; set; }
        public string Unit { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> IsParent { get; set; }
        public string Remark { get; set; }
    
    	[ForeignKey("AssetInfos_ID")]
        public virtual AssetInfos AssetInfos { get; set; }
    }
    
}
