//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBService.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations.Schema;
	using JiYun.Web.Models;
	using System.ComponentModel.DataAnnotations;
    
    public partial class MerchantInfos:BaseModel
    {
        public MerchantInfos()
        {
            this.AccidentalMaintenances = new HashSet<AccidentalMaintenances>();
            this.AssetInfos = new HashSet<AssetInfos>();
        }
    
        public string MerchantName { get; set; }
        public string MerchantCategory { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string Linkman { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AccidentalMaintenances> AccidentalMaintenances { get; set; }
        public virtual ICollection<AssetInfos> AssetInfos { get; set; }
    }
    
}
