//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDBService.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations.Schema;
	using JiYun.Web.Models;
	using System.ComponentModel.DataAnnotations;
    
    public partial class TaskDesignateInfos:BaseModel
    {
        public string TaskSubject { get; set; }
        public string TaskContent { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Starttime { get; set; }
        public Nullable<System.DateTime> Endtime { get; set; }
        public Nullable<int> LoopCategory { get; set; }
        public string TaskPlace { get; set; }
        public Nullable<int> Doer_ID { get; set; }
    
    	[ForeignKey("UserScheduleInfos_ID")]
        public virtual UserScheduleInfos UserScheduleInfos { get; set; }
    }
    
}
